{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.hosts.store }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "moderngreek.fullname" $ }}-store
  labels:
    app: {{ template "moderngreek.name" $ }}-store
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  rules:
    - host: {{ .name }}
      http:
        paths:
          - path: {{ .path }}
            backend:
              serviceName: {{ template "moderngreek.fullname" $ }}-store
              servicePort: http
          - path: /
            backend:
              serviceName: {{ template "moderngreek.fullname" $ }}-public
              servicePort: 80
    - host: www.{{ .name }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "moderngreek.fullname" $ }}-public
              servicePort: 80
  {{- if (and $.Values.ingress.enabled $.Values.ingress.ssl) }}
  tls:
    - secretName: letsencrypt-staging
      hosts:
        - {{ .name }}
  {{- end }}
---
{{- end }}
{{- end }}
