{{- if .Values.ingress.enabled }}
{{- $host := (index .Values.ingress.hosts.api 0) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "moderngreek.fullname" . }}-api
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if (and .Values.ingress.enabled .Values.ingress.tls) }}
    {{- if (empty .Values.ingress.certificate) }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.issuer.name }}
    kubernetes.io/tls-acme: 'true'
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    {{- end }}
  labels:
    app: {{ template "moderngreek.name" . }}-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ $host.name }}
      http:
        paths:
          - path: {{ $host.path }}
            backend:
              serviceName: {{ template "moderngreek.fullname" . }}-api
              servicePort: http
  {{- if (and .Values.ingress.enabled .Values.ingress.tls) }}
  tls:
    - secretName: {{ template "moderngreek.certificate" . }}-api
      hosts:
        - {{ $host.name }}
  {{- end }}
{{- end }}
