apiVersion: v1
kind: Secret
metadata:
  name: {{ template "moderngreek.fullname" . }}
  labels:
    app: {{ template "moderngreek.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- $mongo := .Values.config.mongo }}
  mongo_password: {{ $mongo.password | b64enc }}
  mongo_url: {{ (template "moderngreek.mongo_url" .) | b64enc }}
