apiVersion: v1
kind: Secret
metadata:
  name: {{ template "moderngreek.fullname" . }}
  labels:
    app: {{ template "moderngreek.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- $mongo := .Values.config.mongo }}
  mongo_password: {{ $mongo.password | b64enc }}
  mongo_session_url: {{ ((eq $mongo.sessionUrl true) | ternary "true" $mongo.sessionUrl) | b64enc }}
  mongo_url: {{ ((eq $mongo.url true) | ternary "true" $mongo.url) | b64enc }}
