apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "moderngreek.fullname" . }}-certs
  labels:
    app: {{ template "moderngreek.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pushKey.p8: {{ .Values.config.apnPushKey }}
