{{- if .Values.config.mongo.internal }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "moderngreek.fullname" . }}-mongo
  labels:
    app: {{ template "moderngreek.name" . }}-mongo
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "moderngreek.name" . }}-mongo
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "moderngreek.fullname" . }}-mongo
          image: {{ .Values.images.mongo.repository }}:{{ .Values.images.mongo.tag }}
          imagePullPolicy: {{ .Values.images.mongo.pullPolicy }}
          ports:
            - name: container
              containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
              subPath: mongo
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "moderngreek.fullname" . }}
                  key: mongo_database
          livenessProbe:
            tcpSocket:
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            tcpSocket:
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "moderngreek.fullname" . ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
