apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "moderngreek.fullname" . }}-store
  labels:
    app: {{ template "moderngreek.name" . }}-store
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "moderngreek.name" . }}-store
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "moderngreek.name" . }}-store
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: dockerhub
      containers:
        - name: {{ template "moderngreek.fullname" . }}-store
          image: {{ .Values.images.store.repository }}:{{ .Values.images.store.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 9001
          env: []
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
