apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "moderngreek.fullname" . }}-api
  labels:
    app: {{ template "moderngreek.name" . }}-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "moderngreek.name" . }}-api
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "moderngreek.fullname" . }}-api
          image: {{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}
          imagePullPolicy: {{ .Values.images.api.pullPolicy }}
          ports:
            - name: container
              containerPort: 1337
          env:
            - name: MONGO_PASSWORD
              value: {{ .Values.config.mongoPassword }}
            - name: APN_KEY_ID
              value: {{ .Values.config.apnKeyId }}
            - name: APN_TEAM_ID
              value: {{ .Values.config.apnTeamId }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          configMap:
            name: {{ template "moderngreek.fullname" . }}
