images:
  api:
    repository: moderngreekus/rest-api
    tag: latest
    pullPolicy: Always
  dashboard:
    repository: moderngreekus/dashboard
    tag: latest
    pullPolicy: Always
  store:
    repository: moderngreekus/store
    tag: latest
    pullPolicy: Always

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

ingress:
  enabled: false
  ssl: false
  hosts:
    api:
      - name: ''
        path: /
    dashboard:
      - name: ''
        path: /
    store:
      - name: ''
        path: /store

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    api:
      http: ''
    dashboard:
      http: ''
    store:
      http: ''

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi

config:
  mongoPassword: ''
  apnKeyId: ''
  apnTeamId: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
